apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kube/cert.yaml
- kube/ingress.yaml
- kube/deployment.yaml

configMapGenerator:
- name: node-campanha-smart-env
  env: .env.prod